version: "3"
services:
  db:
    image: 'postgres:latest'
    container_name: db
    ports: 
      - "5432:5432"
    volumes:
      - ./server/database:/var/lib/postgresql/data
    networks:
      - checkpoint
    environment:
      POSTGRES_PASSWORD: bacon
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres 

  server:
    build: ./server
    container_name: server
    volumes:
      - ./server:/app
    ports:
      - "3001:3000"
    networks:
      - checkpoint
    environment:
      DB_CONNECTION_STRING: postgres://postgres:bacon@db:5432/postgres
    depends_on:
      - db

  frontend:
    build: ./front-end
    container_name: frontend
    volumes:
      - ./front-end:/app
    ports:
      - "3000:3000"
    networks:
      - checkpoint
    depends_on:
      - server

networks:
  checkpoint:
    driver: bridge